# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
department = Department.create(name: 'admin')

User.create(department_id: department.id, name: 'admin', account: 'admin', pwd: 'admin')

Saletype.create([{ name: '寄售' }, { name: '收购' }, { name: '置换' }])

Newsfrom.create(name: '来电来访')
Newsfrom.create(name: '主动来店')
Newsfrom.create(name: '朋友介绍')
Newsfrom.create(name: '公司网站')
Newsfrom.create(name: '报纸广告')
Newsfrom.create(name: '合作商户')
Newsfrom.create(name: '老客户介绍')

CooperateType.create(name: '汽车厂商')
CooperateType.create(name: '4S经销商')
CooperateType.create(name: '银行')
CooperateType.create(name: '保险公司')
CooperateType.create(name: '金融担保公司')
CooperateType.create(name: '维修汽配厂')
CooperateType.create(name: '租车公司')
CooperateType.create(name: '婚庆礼仪公司')
CooperateType.create(name: '政府单位')
CooperateType.create(name: '其他')

CooperateRelation.create(name: '合作伙伴')
CooperateRelation.create(name: '供应商')

CooperateLevel.create(name: '一级')
CooperateLevel.create(name: '二级')
CooperateLevel.create(name: '三级')

Rating.create(name: '普通车源')
Rating.create(name: '优质车源')

Transmission.create(name: '手自一体')
Transmission.create(name: '自动')
Transmission.create(name: '手动')
Transmission.create(name: '双离合')

CcUnit.create(name: 'L')
CcUnit.create(name: 'T')

Color.create(name: '黑色', color: '#333333')
Color.create(name: '红色', color: '#CC0000')
Color.create(name: '白色', color: '#ffffff')
Color.create(name: '咖啡色', color: '#F1E9C8')
Color.create(name: '绿色', color: '#339933')
Color.create(name: '蓝色', color: '#0066CC')
Color.create(name: '黄色', color: '#FF9900')
Color.create(name: '银白色', color: '#F5F5F3')
Color.create(name: '灰色', color: '#E0E2E2')
Color.create(name: '棕色', color: '#CC9966')

InteriorColor.create(name: '黑色', color: '#333333')
InteriorColor.create(name: '灰色', color: '#CCCCCC')
InteriorColor.create(name: '浅黄', color: '#F3ECD2')
InteriorColor.create(name: '棕红', color: '#CC6600')

BodyClass.create(name: '两厢')
BodyClass.create(name: '三厢')

EmissionStandard.create(name: '国2排放(欧2)')
EmissionStandard.create(name: '国3排放(欧3)')
EmissionStandard.create(name: '国4排放(欧4)')
EmissionStandard.create(name: '国5排放(欧5)')
EmissionStandard.create(name: '其他')

UseNature.create(name: '非营运')
UseNature.create(name: '营运')
UseNature.create(name: '单位用车')
UseNature.create(name: '公务车辆')

CompulsoryCompany.create(name: '平安车险')
CompulsoryCompany.create(name: '太平洋车险')

BusinessInfo.create(name: '车损险')
BusinessInfo.create(name: '第三者责任险')
BusinessInfo.create(name: '盗抢险')
BusinessInfo.create(name: '座位险')
BusinessInfo.create(name: '玻璃险')
BusinessInfo.create(name: '划痕险')
BusinessInfo.create(name: '自燃险')
BusinessInfo.create(name: '不计免赔险')

BusinessCompany.create(name: '平安保险')
BusinessCompany.create(name: '泰康保险')

Standard.create(name: '基本型')
Standard.create(name: '舒适型')
Standard.create(name: '豪华型')
Standard.create(name: '最高配置')

Safety.create(name: 'EBD（制动力分配系统）')
Safety.create(name: 'ABS（防抱死刹车系统）')
Safety.create(name: 'ESP（电子稳定装置）')
Safety.create(name: 'ASR（驱动防滑系统）')
Safety.create(name: 'EDS（电子差速锁）')
Safety.create(name: 'TCS（牵引力控制系统）')
Safety.create(name: '4WD（四轮驱动）')
Safety.create(name: '安全气囊')

Comfort.create(name: '天窗')
Comfort.create(name: '电动车窗')
Comfort.create(name: '多功能方向盘')
Comfort.create(name: '电加热/出风座椅')
Comfort.create(name: '真皮座椅')
Comfort.create(name: '恒温空调')
Comfort.create(name: '电调空调')
Comfort.create(name: '车载冰箱')
Comfort.create(name: '车载电话')
Comfort.create(name: '氙气灯')
Comfort.create(name: '电视')
Comfort.create(name: '后排座椅安全带')

Function.create(name: 'MP3')
Function.create(name: 'DVD')
Function.create(name: 'CD')
Function.create(name: 'GPS导航')
Function.create(name: 'CCS定速巡航')
Function.create(name: 'X扬声器')
Function.create(name: '大灯高度可调')
Function.create(name: '倒车雷达')
Function.create(name: '倒车影像系统')
Function.create(name: '助力转向')
Function.create(name: '行车电脑显示')
Function.create(name: '防盗设备')
Function.create(name: '前后盘式刹车')
Function.create(name: '高位刹车灯')
Function.create(name: '防炫目后视镜')
Function.create(name: '铝合金轮毂')
Function.create(name: '中控锁')
Function.create(name: '钥匙遥控')